#!/usr/bin/env tsx
/**
 * Regenerate the committed cryptographic test vectors.
 *
 *     pnpm exec tsx scripts/gen-vectors.ts
 *
 * The vectors pin the exact bytes this implementation produces for
 * canonicalization, digests and Ed25519 JWS signing. `crypto/vectors.test.ts`
 * asserts we still reproduce them.
 *
 * They exist because the audit-log verifier is designed to be a separate
 * program — potentially a separate language — and a hash mismatch discovered
 * on day twelve is unrecoverable. Any change to this file is a change to the
 * wire format and must be treated as one.
 *
 * The keys below are FIXED AND PUBLIC. They are test fixtures with no value
 * and must never be used for anything real.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { JsonValue } from "../src/crypto/canonical.js";
import { canonical } from "../src/crypto/canonical.js";
import { digestJson, digestString } from "../src/crypto/digest.js";
import { sign } from "../src/crypto/jws.js";
import { importPrivateKey } from "../src/crypto/keys.js";

/**
 * RFC 8032 §7.1 TEST 1 key material, re-encoded from hex to base64url.
 * Public, worthless, deliberately fixed.
 */
export const FIXED_ED25519_JWK = {
  kty: "OKP",
  crv: "Ed25519",
  d: "nWGxne_9WmC6hEr0kuwsxERJxWl7MmkZcDusAxyuf2A",
  x: "11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo",
} as const;

/** A pinned P-256 key, used only to prove ES256 signatures verify. */
export const FIXED_ES256_JWK = {
  kty: "EC",
  crv: "P-256",
  d: "2jQVtVcTzfVRftX3YfkMMUdpTXjqnsnmnfYpizXKSEU",
  x: "jsLGjB1EBnjzaS_usW3dumvfoLh6IlhY0Q2qcfDQ6FI",
  y: "IKPwYvEmZl2M3kZ72FDXm3q9LCxsqXX5nebjoDUaEs4",
} as const;

const CANONICAL_CASES: Record<string, JsonValue> = {
  empty_object: {},
  empty_array: { a: [] },
  key_ordering: { z: 1, a: 2, M: 3, m: 4, "0": 5 },
  nested_ordering: { b: { d: 1, c: 2 }, a: [3, { z: 1, y: 2 }] },
  ecmascript_numbers: {
    // The narrowing to 333333333.3333333 is the behaviour under test, not an accident.
    // biome-ignore lint/correctness/noPrecisionLoss: RFC 8785 §3.2.2.3 vector
    n: [333333333.33333329, 1e30, 4.5, 2e-3, 1e-27, 0, -0],
  },
  utf16_code_unit_ordering: {
    "\u20ac": "Euro Sign",
    "\r": "Carriage Return",
    "\u000a": "Newline",
    "1": "One",
    "\u00f6": "Latin Small Letter O With Diaeresis",
    "\ufb33": "Hebrew Letter Dalet With Dagesh",
    "</script>": "Browser Challenge",
  },
  literals: { l: [null, true, false] },
  // Shaped like a real closed mandate: money is a string plus a currency,
  // never a number, so no float can ever enter the hashed bytes.
  mandate_like: {
    vct: "dev.countersign.mandate.spend.1",
    iss: "agent:pricing-bot",
    aud: "https://countersign.example/agent-commerce",
    jti: "01K3QF8ZZ0P6QW1E4RT7YUIOPA",
    iat: 1755700421,
    exp: 1755700541,
    amount: { amount: "1499000", currency: "INR" },
    payee: { id: "vnd_1042" },
  },
};

const DIGEST_STRING_CASES: Record<string, string> = {
  abc: "abc",
  empty: "",
  unicode: "₹1,499.00 — देय",
};

async function main(): Promise<void> {
  const ed25519 = await importPrivateKey(FIXED_ED25519_JWK as never, "Ed25519");
  const es256 = await importPrivateKey(FIXED_ES256_JWK as never, "ES256");

  const canonicalVectors = Object.fromEntries(
    Object.entries(CANONICAL_CASES).map(([name, input]) => [
      name,
      { input, canonical: canonical(input), sha256_b64u: digestJson(input) },
    ]),
  );

  const digestVectors = Object.fromEntries(
    Object.entries(DIGEST_STRING_CASES).map(([name, input]) => [
      name,
      { input, sha256_b64u: digestString(input) },
    ]),
  );

  const jwsPayload = CANONICAL_CASES.mandate_like as JsonValue;
  const typ = "application/countersign-mandate+jws";

  const vectors = {
    $comment:
      "Generated by scripts/gen-vectors.ts. Keys are public test fixtures with no value. " +
      "A change to this file is a change to the wire format.",
    generator: "scripts/gen-vectors.ts",
    spec: {
      canonicalization: "RFC 8785 (JCS)",
      digest: "SHA-256, base64url without padding (RFC 7515 Appendix C)",
      jws: "RFC 7515 compact serialization over the JCS payload",
      thumbprint: "RFC 7638, SHA-256",
    },
    canonicalization: canonicalVectors,
    digest_utf8: digestVectors,
    keys: {
      ed25519: { public: { ...ed25519.publicJwk }, kid: ed25519.kid },
      es256: { public: { ...es256.publicJwk }, kid: es256.kid },
    },
    jws: {
      // Ed25519 is deterministic: the same key and payload always yield the
      // same bytes, so this signature is a genuine cross-implementation
      // anchor.
      ed25519_deterministic: {
        typ,
        payload: jwsPayload,
        compact: await sign(jwsPayload, ed25519, typ),
      },
      // ES256 is deliberately non-deterministic (see keys.ts), so a byte-exact
      // vector is impossible. This one is asserted to VERIFY, not to match.
      es256_must_verify: {
        typ,
        payload: jwsPayload,
        compact: await sign(jwsPayload, es256, typ),
      },
    },
  };

  const out = join(dirname(fileURLToPath(import.meta.url)), "..", "test", "vectors", "crypto.json");
  writeFileSync(out, `${JSON.stringify(vectors, null, 2)}\n`, "utf8");
  console.log(`wrote ${out}`);
}

await main();
